name: dompetin

services:
  postgres:
    image: postgres:16.0-alpine
    platform: linux/amd64
    container_name: dompetin-postgres
    environment:
      POSTGRES_DB: dompetin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dompetin_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  dompetin_postgres_data:
